/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class c_newndk_JNI */

#ifndef _Included_c_newndk_JNI
#define _Included_c_newndk_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     c_newndk_JNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_c_newndk_JNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
