/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class c_newndk_JavaCall */

#ifndef _Included_c_newndk_JavaCall
#define _Included_c_newndk_JavaCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     c_newndk_JavaCall
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_c_newndk_JavaCall_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
